# Generated by Django 4.2.5 on 2023-09-23 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City_Obj',
            fields=[
                ('ID_Object', models.IntegerField(primary_key=True, serialize=False)),
                ('Name_Obj', models.CharField(help_text='Input name obj', max_length=100)),
                ('Region', models.CharField(help_text='Input name region', max_length=100)),
                ('Year', models.IntegerField(default=1800, help_text='Input year opening')),
                ('Opener', models.CharField(help_text='Input name opener', max_length=100)),
                ('Status', models.CharField(choices=[('del', 'Удален'), ('ope', 'Действует')], default='ope', help_text='Status Obj', max_length=3)),
                ('Image_Url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expeditions',
            fields=[
                ('ID_Expedition', models.IntegerField(primary_key=True, serialize=False)),
                ('Name_Exp', models.CharField(help_text='Input name expedition', max_length=150)),
                ('DateStart', models.DateField(default='01.01.1800', help_text='Дата начала экспедиции')),
                ('DateEnd', models.DateField(default='01.01.1800', help_text='Дата конца экспедиции')),
                ('DateApproving', models.DateField(default=models.DateField(default='01.01.1800', help_text='Дата начала экспедиции'), help_text='Дата утверждения экспедиции')),
                ('Status', models.CharField(choices=[('in', 'Введён'), ('wo', 'В работе'), ('en', 'Завершён'), ('ca', 'Отменён'), ('de', 'Удалён')], default='in', help_text='Status Expedition', max_length=2)),
                ('Leader', models.CharField(help_text='Input name leader', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('ID_User', models.IntegerField(primary_key=True, serialize=False)),
                ('Is_Super', models.BooleanField(default=False)),
                ('Username', models.CharField(help_text='Input username', max_length=50)),
                ('Login', models.CharField(help_text='Input login', max_length=50)),
                ('Password', models.CharField(help_text='Input password', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectExpedition',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('ID_Exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.expeditions')),
                ('ID_Obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.city_obj')),
            ],
        ),
        migrations.AddField(
            model_name='expeditions',
            name='Moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.users'),
        ),
    ]
