# Generated by Django 4.2.5 on 2023-10-15 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('ID_Expedition', models.IntegerField(primary_key=True, serialize=False)),
                ('Name_Exp', models.CharField(help_text='Input name expedition', max_length=150)),
                ('DateStart', models.DateTimeField(auto_now_add=True, help_text='Дата начала экспедиции')),
                ('DateEnd', models.DateTimeField(auto_now=True, help_text='Дата конца экспедиции', null=True)),
                ('DateApproving', models.DateField(auto_now=True, help_text='Дата утверждения экспедиции', null=True)),
                ('Status', models.CharField(choices=[('in', 'Введён'), ('wo', 'В работе'), ('en', 'Завершён'), ('ca', 'Отменён'), ('de', 'Удалён')], default='in', help_text='Status Expedition', max_length=2)),
                ('Leader', models.CharField(help_text='Input name leader', max_length=100)),
                ('Describe', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('ID_Object', models.IntegerField(primary_key=True, serialize=False)),
                ('Name_Obj', models.CharField(help_text='Input name obj', max_length=100)),
                ('Region', models.CharField(help_text='Input name region', max_length=100)),
                ('Year', models.IntegerField(default=1800, help_text='Input year opening')),
                ('Opener', models.CharField(help_text='Input name opener', max_length=100)),
                ('Status', models.CharField(choices=[('del', 'Удален'), ('ope', 'Действует')], default='ope', help_text='Status Obj', max_length=3)),
                ('Image_Url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('ID_User', models.IntegerField(primary_key=True, serialize=False)),
                ('Is_Super', models.BooleanField(default=False)),
                ('Username', models.CharField(help_text='Input username', max_length=50)),
                ('Login', models.CharField(help_text='Input login', max_length=50)),
                ('Password', models.CharField(help_text='Input password', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Programm',
            fields=[
                ('Number', models.IntegerField(help_text='Порядковый номер', null=True)),
                ('ID_Exp', models.ForeignKey(db_column='ID_Exp', on_delete=django.db.models.deletion.CASCADE, to='lab.expedition')),
                ('ID_Obj', models.ForeignKey(db_column='ID_Obj', on_delete=django.db.models.deletion.CASCADE, to='lab.object')),
            ],
        ),
        migrations.AddField(
            model_name='expedition',
            name='ID_Creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ID_Author', to='lab.users'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='Moderator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Moderator', to='lab.users'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='Objects',
            field=models.ManyToManyField(through='lab.Programm', to='lab.object'),
        ),
    ]
