# Generated by Django 4.2.5 on 2023-11-12 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='ID_Creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ID_Author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='Moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Moderator', to=settings.AUTH_USER_MODEL),
        ),
    ]
