# Generated by Django 4.2.5 on 2023-09-26 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestOE',
            fields=[
                ('Number', models.IntegerField(help_text='Порядковый номер', null=True)),
                ('ID_Exp', models.ForeignKey(db_column='ID_Exp', on_delete=django.db.models.deletion.DO_NOTHING, to='lab.expeditions')),
                ('ID_Obj', models.ForeignKey(db_column='ID_Obj', on_delete=django.db.models.deletion.DO_NOTHING, to='lab.city_obj')),
            ],
        ),
    ]
