# Generated by Django 4.2.5 on 2023-09-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expeditions',
            name='Describe',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='expeditions',
            name='DateApproving',
            field=models.DateField(default='01.01.1800', help_text='Дата утверждения экспедиции'),
        ),
    ]
