# Generated by Django 4.2.5 on 2023-11-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_alter_expedition_id_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='Archive',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
