# Generated by Django 4.2.5 on 2023-09-26 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_testoe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ObjectExpedition',
        ),
    ]
