# Generated by Django 4.2.5 on 2023-09-24 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_expeditions_describe_alter_expeditions_dateapproving'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expeditions',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
    ]
