# Generated by Django 4.2.5 on 2023-09-26 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_delete_objectexpedition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestOE',
            new_name='Obj_Exp',
        ),
    ]
