# Generated by Django 4.2.5 on 2023-10-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_alter_expedition_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='Describe',
            field=models.CharField(default='...', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='ID_Expedition',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='Leader',
            field=models.CharField(default='ФИО Лидера', help_text='Input name leader', max_length=100),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='Name_Exp',
            field=models.CharField(default='Название экспедиции', help_text='Input name expedition', max_length=150),
        ),
    ]
