# Generated by Django 4.2.5 on 2023-09-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_alter_expeditions_options_alter_users_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expeditions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]
