# Generated by Django 4.2.5 on 2023-09-25 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_alter_expeditions_options_alter_users_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expeditions',
            old_name='Moderator',
            new_name='ID_User',
        ),
    ]
