# Generated by Django 4.2.5 on 2023-09-26 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_rename_testoe_obj_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obj_exp',
            name='ID_Exp',
            field=models.ForeignKey(db_column='ID_Exp', on_delete=django.db.models.deletion.CASCADE, to='lab.expeditions'),
        ),
        migrations.AlterField(
            model_name='obj_exp',
            name='ID_Obj',
            field=models.ForeignKey(db_column='ID_Obj', on_delete=django.db.models.deletion.CASCADE, to='lab.city_obj'),
        ),
    ]
