# Generated by Django 4.2.5 on 2023-10-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_alter_expedition_describe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programm',
            name='Number',
            field=models.IntegerField(default=1, help_text='Порядковый номер', null=True),
        ),
    ]
