# Generated by Django 4.2.5 on 2023-09-25 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_rename_moderator_expeditions_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expeditions',
            name='ID_User',
        ),
        migrations.AddField(
            model_name='expeditions',
            name='ID_Creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ID_Author', to='lab.users'),
        ),
        migrations.AddField(
            model_name='expeditions',
            name='Moderator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Moderator', to='lab.users'),
        ),
    ]
