# Generated by Django 4.2.5 on 2023-10-20 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_alter_expedition_dateapproving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='DateApproving',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 20, 12, 51, 12, 683535, tzinfo=datetime.timezone.utc), help_text='Дата утверждения экспедиции', null=True),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='DateStart',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Дата начала экспедиции'),
        ),
    ]
