# Generated by Django 4.2.5 on 2023-10-22 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_alter_expedition_dateapproving_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='DateApproving',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='Дата утверждения экспедиции', null=True),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='DateEnd',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='Дата конца экспедиции', null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='Image_Url',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
