# Generated by Django 4.2.5 on 2023-11-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_alter_expedition_dateapproving_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='Image_Url',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
